### ISSUE TITLE
async methods should be declared as returning Promise

### ISSUE THREAD

**Issue by wh0** [khalby786/jsoning#24] opened 2021-10-02 07:02 UTC
## Describe the bug
the async-ness is an internal implementation detail. as far as callers and typescript are concerned, they're methods that return a Promise.

## Reproducible code sample (if applicable)

```javascript
const c = db.clear();
// c is Promise, not boolean
```

## Expected behavior
n/a

## Further details
- Jsoning version: master branch
- Node.js version: n/a
- Operating system: n/a

## Additional context
in jsoning.d.ts

**Comment by khalby786** [comment] 2021-10-02 09:20
@wh0 how do you suggest that I implement this?

**Comment by pufferfish101007** [comment] 2021-10-02 10:03
Fairly sure #19 fixes this, however it probably needs to update the jsdoc as well

**Comment by khalby786** [comment] 2022-01-31 05:07
Duplicate of https://github.com/khalby786/jsoning/pull/19

**Comment by khalby786** [comment] 2022-01-31 09:53
Done! https://github.com/khalby786/jsoning/pull/19

**Closed as completed by khalby786** 2022-01-31 09:53 UTC
Labels: bug, help wanted
